micronaut:
  application:
    name: micronaut-jooq-sample
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
    driver-class-name: "org.postgresql.Driver"
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'